# frozen_string_literal: true

Gem::Specification.new do |s|
    s.name = 'map_visualizer'
    s.version     = '1.0.0'
    s.summary     = 'Visualize terrain generated by https://github.com/heppyn/VoxelGame as a map'
    s.author      = 'Lukas Hepner'
    s.email       = 'hepneluk@fit.cvut.cz'
    s.files       = ['lib/map_visualizer.rb', 'lib/map-visualizer/*.rb', 'spec/*.rb',
                     'Gemfile', 'Gemfile.lock']
    s.license     = 'MIT'
  end
