# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name = 'map_visualizer'
  s.version     = '1.0.0'
  s.summary     = 'Visualize terrain generated by https://github.com/heppyn/VoxelGame as a map'
  s.author      = 'Lukas Hepner'
  s.email       = 'hepneluk@fit.cvut.cz'
  s.homepage    = 'https://gitlab.fit.cvut.cz/hepneluk/map-visualizer'
  s.files       = ['lib/map_visualizer.rb',
                   'lib/map-visualizer/biome.rb',
                   'lib/map-visualizer/block_info.rb',
                   'lib/map-visualizer/chunk.rb',
                   'lib/map-visualizer/height.rb',
                   'lib/map-visualizer/loader.rb',
                   'lib/map-visualizer/scene.rb',
                   'lib/map-visualizer/temperature.rb',
                   'lib/map-visualizer/visualizer.rb',
                   'lib/map-visualizer/helpers/image.rb',
                   'lib/map-visualizer/helpers/vec.rb',
                   'spec/loader_test.rb',
                   'spec/scene_test.rb',
                   'spec/vec_test.rb',
                   'spec/visualizer_test.rb',
                   'spec/test_data/biomes.json',
                   'spec/test_data/export.json',
                   'spec/test_data/scene1.json',
                   'Gemfile', 'Gemfile.lock']
  s.license     = 'MIT'
end
